WIP: 70 load balancer
fi-ts/postgreslet pull request #86
Opened 2021-02-10 20:32 UTC by LimKianAn

- `Service LoadBalancer` is created/deleted alongside `Postgres`.
- `Endpoints` are correctly picked up by the labels.
- `nextFreePort()` in *lbmanager.go* works.

@majst01 @eberlep Please comment if the direction is correct.

2021-02-11 06:18 UTC, majst01 commented
LGTM

2021-02-12 12:35 UTC, majst01 commented on api/v1/postgres_types.go
> +	LBSocket LBSocket `json:"lbSocket,omitempty"`
I would prefer Socket instead of LBSocket

2021-02-15 11:53 UTC, eberlep requested changes

2021-02-15 11:53 UTC, eberlep commented on charts/postgreslet/values.yaml
> +  portRangeStart: 31767
Which ports to use as defaults?

2021-02-15 11:53 UTC, eberlep commented on api/v1/postgres_types.go
> +	lb.SetLabels(label)
Add our own custom label here to ease selection in `lbmanager`

2021-02-15 11:53 UTC, eberlep commented on api/v1/postgres_types.go
> +	lb.Spec.Selector = label
Make sure *not* to use our custom label here, as this is the selector for operator-managed pods

2021-02-15 11:53 UTC, eberlep commented on pkg/lbmanager/lbmanager.go
> +const SvcTypeIndex = "spec.type"
Remove this one and use custom label,

2021-02-15 11:53 UTC, eberlep commented on pkg/lbmanager/lbmanager.go
> +		client.MatchingLabels{
Only use custom label here. We won't need the MatchinField then either.

2021-02-15 11:53 UTC, eberlep commented on pkg/operatormanager/operatormanager.go
> +
Add TODO to #83

2021-02-15 11:54 UTC, eberlep commented on charts/postgreslet/values.yaml
> +  portRangeStart: 31767
@majst01 what do you think?

2021-02-15 13:51 UTC, eberlep commented on api/v1/postgres_types.go
> +	"cloud-service": "pgaas",
hmm, how about `{ "postgres.database.fits.cloud/managed-by": "postgreslet"}`?

2021-02-15 14:22 UTC, eberlep approved these changes

2021-02-15 14:22 UTC, merged